# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Casey Lim
author: Casey Lim
keywords: HTML,CSS,XML,JavaScript
email: casey.x.lim@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome! My hobbies include 🎨 making stuff, 📸 looking at stuff, 🎥. and recording stuff. This is my personal blog and folio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username:  xitricite
tumblr_username:  xitricite
twitter_username: xitricite
github_username:  xitricite
youtube_username: UCEaHE6GHVPDvB5os4VMXsgg

reel_video_thumb: https://img.youtube.com/vi/CYktJ75Q_Uw/maxresdefault.jpg
reel_video_url: https://www.youtube.com/embed/CYktJ75Q_Uw

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
